name: cyclic_numbers
description: Cyclic Numbers
version: 0.0.1+1

environment:
  sdk: ">=2.8.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  animations: ^1.0.0+3
  audioplayers: ^0.14.0
  auto_size_text: ^2.1.0
  built_collection: ^4.3.2
  built_value: ^7.0.9
  cached_network_image: ^2.0.0
  cupertino_icons: ^0.1.3
  dartz: ^0.9.0-dev.6
  device_info: ^0.4.1+5
  flutter_bloc: ^3.2.0
  flutter_platform_widgets: ^0.32.4
  flutter_secure_storage: ^3.3.1+1
  http: ^0.12.0+4
  intl: ^0.16.1
  package_info: ^0.4.0+14
  path_provider: ^1.6.1
  rxdart: ^0.23.1
  shared_preferences: ^0.5.6+2
  time: ^1.2.0
  timeago: ^2.0.26
  transparent_image: ^1.0.0
  tuple: ^1.0.3
  uuid: ^2.0.4

dev_dependencies:
  build_runner: ^1.7.4
  built_value_generator: ^7.0.9
  faker: ^1.2.1
  mockito: ^4.1.1
  pedantic: ^1.9.0
  test: ^1.12.0

flutter:
  uses-material-design: true
